### PR TITLE
README: add a Lua example

### PR DESCRIPTION
**Pull request by deltheil**
This should cover the whole set of capabilities of `tds`.

### CODE REVIEW

**Comment by andresy** [comment]
thanks, that is a great start :)

**Comment by deltheil** [comment]
Cool! BTW: is there any reason why `tds` is not listed on [torch/rocks](https://github.com/torch/rocks)?

**Comment by andresy** [comment]
no... i did not take the time to write the doc, nor to include it in rocks yet :(

**Comment by soumith** [comment]
done, added tds to the rocks!

**Comment by deltheil** [comment]
:+1:

**Pull request merged**
