### PR TITLE
tds.AtomicCounter

### PR DESCRIPTION
**Pull request by lake4790k**
Atomic counter that can safely track progress between threads. I'll add `threads.sharedserialize` support once this is merged in `tds`.

### CODE REVIEW

**Comment by deltheil** [comment]
The `THAtomic.h` header from torch is never included which gives `implicit declaration of function ‘THAtomicAddLong’`, etc. warnings. Since `torch7` is not a hard dependency you should condition the availability of this atomic counter with the `HAS_TORCH` macro handled by cmake if torch is detected, e.g. see [this](https://github.com/torch/tds/blob/5382691f13d69cc48df373e1821c1579abf26d4a/tds_hash.c#L8-L10).

**Comment by lake4790k** [comment]
Added the include with `HAS_TORCH` you suggested, also added basic mutex solution if no Torch is present (probably not that useful). This is expected to be used with Torch `threads` of course, so I didn't want to copy the whole `THAtomic` over.

**Comment by deltheil** [comment]
> so I didn't want to copy the whole `THAtomic` over

I see. Another possibility to avoid reinventing the wheel (since anyway pthreads detection should also be included and all of this is already managed by [torch7](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/lib/TH/CMakeLists.txt#L192-L198)) could be to introduce a function like:

```C
bool tds_has_atomic(void) {
#if HAS_TORCH
  return true;
#else
  return false;
#endif
}
```

(and of course bracket the implementation of the various functions with `HAS_TORCH`)

This could be used to avoid creating an atomic counter:

```Lua
-- atomic.lua

function atomic:__new(...)
  if not C.tds_has_atomic() then
    error('atomic counter not available (Torch not found)')
  end
  -- ...
end
```

**Comment by lake4790k** [comment]
Thanks, implemented your suggestion, the implementation now is only available with Torch, because of the dependency on `THAtomic`, otherwise makes no sense to provide a useless implementation.

Should be good to go...?

**Comment by deltheil** [comment]
Cool! Looks good to me.

**Comment by soumith** [comment]
Thanks!

**Pull request merged**
